using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyProduct("WCF.Libraries")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
#if !UNIT_TESTS
[assembly: AssemblyDelaySignAttribute(true)]
[assembly: AssemblyKeyFileAttribute(@"..\..\..\..\..\..\Configuration\Keys\numsite.snk ")]
#endif